apiVersion: v1
kind: Service
metadata:
  name: resource-service-service
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: resource-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

