apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-map
  namespace: k8s-program
data:
  SONG_SERVICE_URL: "http://song-service-service:8081/songs"
  RESOURCE_SERVICE_PORT: "8080"
  RESOURCE_POSTGRES_DB: "jdbc:postgresql://resource-database-service:5432/mp3resource"

  SONG_SERVICE_PORT: "8081"
  SONG_POSTGRES_DB: "jdbc:postgresql://song-database-service:5432/songs"

  RESOURCE_POSTGRES_DB_NAME: "mp3resource"
  SONG_POSTGRES_DB_NAME: "songs"

  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret-config-map
  namespace: k8s-program
data:
  POSTGRES_USER: "cm9vdA=="
  POSTGRES_PASSWORD: "cGFzcw=="



  