apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-service-development
  namespace: k8s-program
  labels:
    app: resource-service-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-service
  template:
    metadata:
      name: resource-service
      namespace: k8s-program
      labels:
        app: resource-service
    spec:
      containers:
        - name: resource-service-container
          image: resource-service-image:v1
          env:
            - name: SONG_SERVICE_URL
              value: http://song-service-service:8081/songs
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
      restartPolicy: Always
      