apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: song-database
  namespace: k8s-program
spec:
  serviceName: "resource-database"
  selector:
    matchLabels:
      app: song-database
  template:
    metadata:
      namespace: k8s-program
      labels:
        app: song-database
    spec:
      containers:
        - name: song-database
          image: postgres:14.9
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: pass
            - name: POSTGRES_DB
              value: songs
          volumeMounts:
            - name: song-database-db-pvc
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: song-database-db-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
