apiVersion: v1
kind: Service
metadata:
  name: song-database-service
  namespace: k8s-program
spec:
  selector:
    app: song-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  