apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service-development
  namespace: k8s-program
  labels:
    app: song-service-development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      name: song-service
      namespace: k8s-program
      labels:
        app: song-service
    spec:
      containers:
        - name: song-service-container
          image: song-service-image:v1
          ports:
            - containerPort: 8081
          imagePullPolicy: Never
      restartPolicy: Always
      