apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "tmp"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: user-pv

  