apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-container
          image: ubuntu
          command:
            - "sleep"
            - "604800"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "tmp"
              name: user-dep-pvc
      restartPolicy: Always
      volumes:
        - name: user-dep-pvc
          persistentVolumeClaim:
            claimName: user-pvc
      